# https://prettier.io/docs/en/options

printWidth: 200
useTabs: true
semi: true
singleQuote: false
quoteProps: consistent
jsxSingleQuote: false
trailingComma: all
bracketSpacing: true
bracketSameLine: true
arrowParens: always
proseWrap: preserve
htmlWhitespaceSensitivity: css
vueIndentScriptAndStyle: true
endOfLine: lf
embeddedLanguageFormatting: auto
singleAttributePerLine: false
