# Declan Chidlow's personal i3status-rust configuration

theme = "gruvbox-dark"
icons = "awesome6"

[[block]]
block = "music"
hide_when_empty = true

[[block]]
block = "sound"
headphones_indicator = true

[[block]]
block = "hueshift"
hue_shifter = "wlgammarelayrs"
click_temp = 4000

[[block]]
block = "backlight"
minimum = 0

[[block]]
block = "net"
on_click = "alacritty -e nmtui"
format = "{signal_strength}"

[[block]]
block = "battery"
hide_missing = true

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
