#!/usr/bin/env bash

# Check if OPUS encoder is installed
if ! command -v opusenc &> /dev/null; then
    echo "An OPUS encoder could not be found but is required to use this script."
    exit 1
fi

echo "Select an option for conversion:"
echo "1) Use default bitrate"
echo "2) Keep current bitrate"
read -r -p "Enter the number corresponding to your choice: " bitrate_choice

case $bitrate_choice in
    1)
        keep_bitrate="false"
		;;
    2)
        keep_bitrate="true"
        ;;
    *)
        echo "Invalid choice. Please run the script again and select a valid option."
        exit 1
        ;;
esac

output_dir="$PWD-converted"
mkdir -p "$output_dir" || { echo "Failed to create directory $output_dir"; exit 1; }

# Convert FLAC files to OPUS with the selected bitrate option
for input_file in ./*.flac; do
    if [ -e "$input_file" ]; then
        output_file="$output_dir/${input_file%.flac}.opus"
        
        echo "Converting $input_file to $output_file..."

        if [ "$keep_bitrate" = "true" ]; then
        	if opusenc "$input_file" "$output_file"; then
            	echo "Successfully converted $input_file to $output_file keeping current bitrate."
			else
                echo "Failed to convert $input_file"
			fi
        else
			if opusenc --bitrate 320 "$input_file" "$output_file"; then
            	echo "Converting $input_file to $output_file with default bitrate..."
			else
                echo "Failed to convert $input_file"
			fi
        fi
    else
        echo "No FLAC files found in the current directory."
        exit 1
    fi
done

echo "All files have been processed."
