bar:
  height: 40
  location: top
  background: 121212ff
  foreground: FCE8C3ff
  font: Lexend:size=24
  spacing: 8

  left:
  - i3:
      sort: ascending
      content:
        "":
          map:
            margin: 2
            default:
            - string:
                text: " {name} "
                foreground: 918175ff
            conditions:
              state == focused:
              - string: 
                  text: " {name} "
                  foreground: FBB829ff
                  deco: {overline: {color: FBB829ff, size: 3}}
              state == urgent:
              - string:
                  text: " {name} "
                  foreground: EF2F27ff
                  deco: {overline: {color: EF2F27ff, size: 3}}
  center:
    - mpd:
        host: /run/user/1000/mpd/socket
        content:
          map:
            margin: 10
            conditions:
              state == offline: 
              - string:
                  text: ""
              state == stopped:
              - string:
                  text: ""
              state == paused:
              - string:
                  text: ""
              state == playing:
              - string:
                  text: " {title} - {album} - {artist} "
                  foreground: 2C78BFff
                  deco: {overline: {color: 2C78BFff, size: 3}}
  
  right:
  - alsa:
      card: default
      mixer: Master
      content:
        map:
          on-click:
            left: amixer set Master toggle
            right: alacritty -e alsamixer
            wheel-up: amixer set Master 1%+
            wheel-down: amixer set Master 1%-
          conditions:
            muted:
            - string:
                text: " VOL: MUT {percent}% "
                foreground: EF2F27ff
                deco: {overline: {color: EF2F27ff, size: 3}}
            ~muted:
            - string:
                text: " VOL: {percent}% "
                foreground: 2C78BFff
                deco: {overline: {color: 2C78BFff, size: 3}}

  - network:
      name: wlp166s0
      content:
        map:
          on-click: alacritty -e nmtui
          conditions:
              state == up:
              - string:
                  text: " NET: UP "
                  foreground: 519F50ff
                  deco: {overline: {color: 519F50ff, size: 3}}
              state == down:
              - string:
                  text: " NET: DWN "
                  foreground: EF2F27ff
                  deco: {overline: {color: EF2F27ff, size: 3}}

  - backlight:
      name: intel_backlight
      content:
      - string:
          text: " LGT: {percent}% "
          foreground: FBB829ff
          deco: {overline: {color: FBB829ff, size: 3}}
          on-click:
            left: xbacklight 50
            right: xbacklight 5
            wheel-up: xbacklight -inc 1
            wheel-down: xbacklight -dec 1

  - battery:
      name: BAT1
      content:
      - ramp:
          on-click: alacritty -e sudo powertop
          tag: capacity
          items:
          - string: {text: " BAT: {capacity}% ", foreground: EF2F27ff, deco: {overline: {color: EF2F27ff, size: 3}}}
          - string: {text: " BAT: {capacity}% ", foreground: D75F00ff, deco: {overline: {color: D75F00ff, size: 3}}}
          - string: {text: " BAT: {capacity}% ", foreground: FBB829ff, deco: {overline: {color: FBB829ff, size: 3}}}
          - string: {text: " BAT: {capacity}% ", foreground: 2C78BFff, deco: {overline: {color: 2C78BFff, size: 3}}}
          - string: {text: " BAT: {capacity}% ", foreground: 519F50ff, deco: {overline: {color: 519F50ff, size: 3}}}

  - clock:
      date-format: "%d/%m"
      content:
      - string: 
          text: " {date} {time} "
          foreground: E02C6Dff
          deco: {overline: {color: E02C6Dff, size: 3}}
