# Declan "Vale" Chidlow's personal configuration file for Yambar
# https://github.com/DeclanChidlow/dotfiles
# https://vale.rocks

bar:
  height: 40
  location: top
  background: 121212ff
  foreground: FCE8C3ff
  font: Lexend:size=24
  spacing: 8

  left:
  - i3:
      sort: ascending
      content:
        "":
          map:
            margin: 2
            default:
            - string:
                text: " {name} "
                foreground: 918175ff
            conditions:
              state == focused:
              - string: 
                  text: " {name} "
                  foreground: FBB829ff
                  deco: {overline: {color: FBB829ff, size: 3}}
              state == urgent:
              - string:
                  text: " {name} "
                  foreground: EF2F27ff
                  deco: {overline: {color: EF2F27ff, size: 3}}

  center:
    - mpd:
        host: /run/user/1000/mpd/socket
        content:
          map:
            margin: 10
            conditions:
              state == offline: 
              - string:
                  text: ""
              state == stopped:
              - string:
                  text: ""
              state == paused:
              - string:
                  text: ""
              state == playing:
              - string:
                  text: " 󰝚 {title} - 󰀥 {album} - 󰠃 {artist} "
                  foreground: 2C78BFff
                  deco: {overline: {color: 2C78BFff, size: 3}}

  right:
  - alsa:
      card: default
      mixer: Master
      content:
        map:
          conditions:
            muted:
            - string:
                text: " 󰖁 {percent}% "
                foreground: EF2F27ff
                deco: {overline: {color: EF2F27ff, size: 3}}
            ~muted:
            - string:
                text: " 󰕾 {percent}% "
                foreground: 2C78BFff
                deco: {overline: {color: 2C78BFff, size: 3}}

  - backlight:
      name: intel_backlight
      content:
      - string:
          text: " 󰌵 {percent}% "
          foreground: FBB829ff
          deco: {overline: {color: FBB829ff, size: 3}}

  - network:
      name: wlp166s0
      content:
        map:
          on-click: alacritty -e nmtui
          conditions:
              state == up:
              - string:
                  text: " 󰖟 "
                  foreground: 519F50ff
                  deco: {overline: {color: 519F50ff, size: 3}}
              state == down:
              - string:
                  text: " 󰪎 "
                  foreground: EF2F27ff
                  deco: {overline: {color: EF2F27ff, size: 3}}

  - battery:
      name: BAT1
      content:
      - ramp:
          tag: capacity
          items:
          - string: {text: " 󱃍 {capacity}% ", foreground: EF2F27ff, deco: {overline: {color: EF2F27ff, size: 3}}}
          - string: {text: " 󰁼 {capacity}% ", foreground: D75F00ff, deco: {overline: {color: D75F00ff, size: 3}}}
          - string: {text: " 󰁾 {capacity}% ", foreground: FBB829ff, deco: {overline: {color: FBB829ff, size: 3}}}
          - string: {text: " 󰂁 {capacity}% ", foreground: 2C78BFff, deco: {overline: {color: 2C78BFff, size: 3}}}
          - string: {text: " 󰁹 {capacity}% ", foreground: 519F50ff, deco: {overline: {color: 519F50ff, size: 3}}}

  - clock:
      date-format: "%d/%m"
      content:
      - string: 
          text: " 󰃭 {date} 󰅐 {time} "
          foreground: E02C6Dff
          deco: {overline: {color: E02C6Dff, size: 3}}
