# Declan Chidlow's personal config for Yambar
# https://github.com/DeclanChidlow/dotfiles
# https://vale.rocks/posts/uses

bar:
  height: 40
  location: top
  spacing: 8
  font: Lexend:size=24
  background: 131111ED
  foreground: FFEAD1ff

  left:
    - i3:
        sort: ascending
        content:
          "":
            map:
              margin: 2
              default:
                - string: { text: " {name} ", foreground: 5E5A5Aff }
              conditions:
                state == focused:
                  - string: { text: " {name} ", foreground: FFAD20ff, deco: { overline: { color: FFAD20ff, size: 3 } } }
                state == urgent:
                  - string: { text: " {name} ", foreground: F13731ff, deco: { overline: { color: F13731ff, size: 3 } } }

  center:
    - mpd:
        host: /run/user/1000/mpd/socket
        content:
          map:
            margin: 10
            conditions:
              state == playing:
                - string: { text: " 󰝚  {title} - 󰀥  {album} - 󰠃  {artist} ", foreground: 3778C0ff, deco: { overline: { color: 3778C0ff, size: 3 } } }

  right:
    - alsa:
        card: default
        mixer: Master
        content:
          map:
            conditions:
              muted:
                - string: { text: " 󰸈  {percent}% ", foreground: F13731ff, deco: { overline: { color: F13731ff, size: 3 } } }
              ~muted:
                ramp:
                  tag: percent
                  items:
                    - string: { text: " 󰕿  {percent}% ", foreground: 2CB7BCff, deco: { overline: { color: 2CB7BCff, size: 3 } } }
                    - string: { text: " 󰖀  {percent}% ", foreground: 2CB7BCff, deco: { overline: { color: 2CB7BCff, size: 3 } } }
                    - string: { text: " 󰕾  {percent}% ", foreground: 2CB7BCff, deco: { overline: { color: 2CB7BCff, size: 3 } } }

    - backlight:
        name: intel_backlight
        content:
          ramp:
            tag: percent
            items:
              - string: { text: " 󱩎  {percent}% ", foreground: FFAD20ff, deco: { overline: { color: FFAD20ff, size: 3 } } }
              - string: { text: " 󱩏  {percent}% ", foreground: FFAD20ff, deco: { overline: { color: FFAD20ff, size: 3 } } }
              - string: { text: " 󱩐  {percent}% ", foreground: FFAD20ff, deco: { overline: { color: FFAD20ff, size: 3 } } }
              - string: { text: " 󱩑  {percent}% ", foreground: FFAD20ff, deco: { overline: { color: FFAD20ff, size: 3 } } }
              - string: { text: " 󱩒  {percent}% ", foreground: FFAD20ff, deco: { overline: { color: FFAD20ff, size: 3 } } }
              - string: { text: " 󱩓  {percent}% ", foreground: FFAD20ff, deco: { overline: { color: FFAD20ff, size: 3 } } }
              - string: { text: " 󱩔  {percent}% ", foreground: FFAD20ff, deco: { overline: { color: FFAD20ff, size: 3 } } }
              - string: { text: " 󱩕  {percent}% ", foreground: FFAD20ff, deco: { overline: { color: FFAD20ff, size: 3 } } }
              - string: { text: " 󱩖  {percent}% ", foreground: FFAD20ff, deco: { overline: { color: FFAD20ff, size: 3 } } }
              - string: { text: " 󰛨  {percent}% ", foreground: FFAD20ff, deco: { overline: { color: FFAD20ff, size: 3 } } }

    - network:
        content:
          map:
            conditions:
              name == wlp166s0:
                map:
                  default:
                    - string: { text: " 󱞒  ", foreground: 58A551ff, deco: { overline: { color: 58A551ff, size: 3 } } }
                  conditions:
                    state == down:
                      - string: { text: " 󰪎  ", foreground: F13731ff, deco: { overline: { color: F13731ff, size: 3 } } }
                    state == up:
                      - string: { text: " 󰖟  ", foreground: 58A551ff, deco: { overline: { color: 58A551ff, size: 3 } } }

    - battery:
        name: BAT1
        anchors:
          discharging: &discharging
            list:
              items:
                - ramp:
                    tag: capacity
                    items:
                      - string: { text: " 󱃍  {capacity}% ", foreground: F13731ff, deco: { overline: { color: F13731ff, size: 3 } } }
                      - string: { text: " 󰁻  {capacity}% ", foreground: F13731ff, deco: { overline: { color: F13731ff, size: 3 } } }
                      - string: { text: " 󰁼  {capacity}% ", foreground: FF7B10ff, deco: { overline: { color: FF7B10ff, size: 3 } } }
                      - string: { text: " 󰁽  {capacity}% ", foreground: FF7B10ff, deco: { overline: { color: FF7B10ff, size: 3 } } }
                      - string: { text: " 󰁾  {capacity}% ", foreground: FFAD20ff, deco: { overline: { color: FFAD20ff, size: 3 } } }
                      - string: { text: " 󰁿  {capacity}% ", foreground: FFAD20ff, deco: { overline: { color: FFAD20ff, size: 3 } } }
                      - string: { text: " 󰂀  {capacity}% ", foreground: 3578C1ff, deco: { overline: { color: 3578C1ff, size: 3 } } }
                      - string: { text: " 󰂁  {capacity}% ", foreground: 3578C1ff, deco: { overline: { color: 3578C1ff, size: 3 } } }
                      - string: { text: " 󰂂  {capacity}% ", foreground: 58A551ff, deco: { overline: { color: 58A551ff, size: 3 } } }
                      - string: { text: " 󰁹  {capacity}% ", foreground: 58A551ff, deco: { overline: { color: 58A551ff, size: 3 } } }
        content:
          map:
            conditions:
              state == unknown:
                <<: *discharging
              state == discharging:
                <<: *discharging
              state == charging:
                - ramp:
                    tag: capacity
                    items:
                      - string: { text: " 󰢜  {capacity}% ", foreground: F13731ff, deco: { overline: { color: F13731ff, size: 3 } } }
                      - string: { text: " 󰂆  {capacity}% ", foreground: F13731ff, deco: { overline: { color: F13731ff, size: 3 } } }
                      - string: { text: " 󰂇  {capacity}% ", foreground: FF7B10ff, deco: { overline: { color: FF7B10ff, size: 3 } } }
                      - string: { text: " 󰂈  {capacity}% ", foreground: FF7B10ff, deco: { overline: { color: FF7B10ff, size: 3 } } }
                      - string: { text: " 󰢝  {capacity}% ", foreground: FFAD20ff, deco: { overline: { color: FFAD20ff, size: 3 } } }
                      - string: { text: " 󰂉  {capacity}% ", foreground: FFAD20ff, deco: { overline: { color: FFAD20ff, size: 3 } } }
                      - string: { text: " 󰢞  {capacity}% ", foreground: 3578C1ff, deco: { overline: { color: 3578C1ff, size: 3 } } }
                      - string: { text: " 󰂊  {capacity}% ", foreground: 3578C1ff, deco: { overline: { color: 3578C1ff, size: 3 } } }
                      - string: { text: " 󰂋  {capacity}% ", foreground: 58A551ff, deco: { overline: { color: 58A551ff, size: 3 } } }
                      - string: { text: " 󰂅  {capacity}% ", foreground: 58A551ff, deco: { overline: { color: 58A551ff, size: 3 } } }
              state == full:
                - string: { text: " 󱈏  {capacity}% ", foreground: 58A551ff, deco: { overline: { color: 58A551ff, size: 3 } } }

    - clock:
        date-format: "%d/%m"
        content:
          - string: { text: " 󰃭  {date} 󰅐  {time} ", foreground: E23572ff, deco: { overline: { color: E23572ff, size: 3 } } }
