# Declan "Vale" Chidlow's personal configuration file for Yambar
# https://github.com/DeclanChidlow/dotfiles
# https://vale.rocks

bar:
  height: 40
  location: top
  background: 131111ff
  foreground: FFEAD0ff
  font: Lexend:size=24
  spacing: 8

  left:
  - i3:
      sort: ascending
      content:
        "":
          map:
            margin: 2
            default:
            - string:
                text: " {name} "
                foreground: 5E5A5Aff
            conditions:
              state == focused:
              - string: 
                  text: " {name} "
                  foreground: FFAD1Fff
                  deco: {overline: {color: FFAD1Fff, size: 3}}
              state == urgent:
              - string:
                  text: " {name} "
                  foreground: F13731ff
                  deco: {overline: {color: F13731ff, size: 3}}

  center:
    - mpd:
        host: /run/user/1000/mpd/socket
        content:
          map:
            margin: 10
            conditions:
              state == offline: 
              - string:
                  text: ""
              state == stopped:
              - string:
                  text: ""
              state == paused:
              - string:
                  text: ""
              state == playing:
              - string:
                  text: " 󰝚 {title} - 󰀥 {album} - 󰠃 {artist} "
                  foreground: 3578C1ff
                  deco: {overline: {color: 3578C1ff, size: 3}}

  right:
  - alsa:
      card: default
      mixer: Master
      content:
        map:
          conditions:
            muted:
            - string:
                text: " 󰖁 {percent}% "
                foreground: F13731ff
                deco: {overline: {color: F13731ff, size: 3}}
            ~muted:
            - string:
                text: " 󰕾 {percent}% "
                foreground: 3578C1ff
                deco: {overline: {color: 3578C1ff, size: 3}}

  - backlight:
      name: intel_backlight
      content:
      - string:
          text: " 󰌵 {percent}% "
          foreground: FFAD1Fff
          deco: {overline: {color: FFAD1Fff, size: 3}}

  - network:
      name: wlp166s0
      content:
        map:
          conditions:
              state == up:
              - string:
                  text: " 󰖟 "
                  foreground: 58A551ff
                  deco: {overline: {color: 58A551ff, size: 3}}
              state == down:
              - string:
                  text: " 󰪎 "
                  foreground: F13731ff
                  deco: {overline: {color: F13731ff, size: 3}}

  - battery:
      name: BAT1
      content:
      - ramp:
          tag: capacity
          items:
          - string: {text: " 󱃍 {capacity}% ", foreground: F13731ff, deco: {overline: {color: F13731ff, size: 3}}}
          - string: {text: " 󰁼 {capacity}% ", foreground: F56E00ff, deco: {overline: {color: F56E00ff, size: 3}}}
          - string: {text: " 󰁾 {capacity}% ", foreground: FFAD1Fff, deco: {overline: {color: FFAD1Fff, size: 3}}}
          - string: {text: " 󰂁 {capacity}% ", foreground: 3578C1ff, deco: {overline: {color: 3578C1ff, size: 3}}}
          - string: {text: " 󰁹 {capacity}% ", foreground: 58A551ff, deco: {overline: {color: 58A551ff, size: 3}}}

  - clock:
      date-format: "%d/%m"
      content:
      - string: 
          text: " 󰃭 {date} 󰅐 {time} "
          foreground: E23672ff
          deco: {overline: {color: E23672ff, size: 3}}
