# Declan "Vale" Chidlow's personal configuration file for Macchina
# https://github.com/DeclanChidlow/dotfiles
# https://vale.rocks

theme = "Default"

show = ["Kernel", "Packages", "Uptime", "ProcessorLoad", "Memory", "Battery"]
